name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v7

            - name: install cowsay
              run: sudo apt-get update && sudo apt-get install -y cowsay

            - name: display ASCII
              run: cowsay "Hello from GitHub Actions! 🐄" >> cow.txt

            - name: Test file exist
              run: grep -i "hello" cow.txt

            - name: read file 
              run: cat cow.txt

            - name: display files
              run: ls -l

            

            # - name: welcome message
            #   run: echo "welcome"

            # - name: list files
            #   run: ls

            # - name: display files
            #   run: cat README.md

            
